# Album information
title = "Test album"
galleries = ["test gallery", "all"]
public = true

# Image information
[[images]]
file = "exported/IMG_12345.jpg"
date = 2020-01-10 12:03:57Z
description = "A random test image"
cover = true
banner = true

[[images]]
file = "exported/IMG_54321.jpg"
date = 2020-01-10 12:04:03Z
description = "A random test image taken shortly after"
cover = false
banner = false

[[images]]
file = "exported/IMG_54321.jpg"
date = 2020-01-11 09:45:14Z
description = "A random test image taken the day after"
cover = true
banner = false
